settings: setup.sh: modified the condition for `makelink which' settings: which: echo -> printf settings: which: support for arguments containing a slash
git-svn-id: https://subversion.assembla.com/svn/magicant/settings@120 9a5e03f8-c55e-0410-a490-9d27d325e308

diff --git a/which b/which
--- a/which
+++ b/which
@@ -9,7 +9,7 @@ if [ x"$1" = x"--" ]; then
 	shift
 else
 	case "$1" in
-		-*) echo "$0: invalid option: $1" >&2; exit 2
+		-*) printf '%s: invalid option: %s\n' "$0" "$1" >&2; exit 2
 	esac
 fi
 
@@ -18,18 +18,28 @@ found=true
 for cmd
 do
 	foundsub=false
-	for dir in $PATH
-	do
-		full="${dir:-.}/$cmd" 
-		if [ -x "$full" ]; then
+	case $cmd in
+	*/*)
+		if [ -x "$cmd" ]; then
 			foundsub=true
-			echo "$full"
-			$all || break
+			printf '%s\n' "$cmd"
 		fi
-	done
+		;;
+	*)
+		for dir in $PATH
+		do
+			full="${dir:-.}/$cmd" 
+			if [ -x "$full" ]; then
+				foundsub=true
+				printf '%s\n' "$full"
+				$all || break
+			fi
+		done
+		;;
+	esac
 	$foundsub || found=false
 done
 
 $found
 
-# vim: ts=4 sw=2 sts=2
+# vim: ts=4 sw=4 sts=4
